export const ADD_PLAYER = 'ADD_PLAYER';
export const SAVE_NAME_INPUT = 'SAVE_NAME_INPUT';
export const SAVE_EMAIL_INPUT = 'SAVE_EMAIL_INPUT';
export const CALCULATE_RANDOMIZE = 'CALCULATE_RANDOMIZE';
export const POST_RESULTS_ON_EMAILS = 'POST_RESULTS_ON_EMAILS';
